console.log(typeof "John");
console.log(typeof 3.14);
console.log(typeof NaN);
console.log(typeof false);
console.log(typeof [1, 2, 3, 4]);
console.log(typeof { name: "John", age: 34 });
console.log(typeof new Date());
console.log(typeof function () {});
console.log(typeof null);
console.log(typeof myCar);
